import DOMPurify from "dompurify";

/**
 * Sanitizes HTML to prevent XSS when rendering with dangerouslySetInnerHTML.
 * Allows safe tags/attributes only (strips scripts, event handlers, etc.).
 */
export function sanitizeHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty, {
    ALLOWED_TAGS: [
      "div",
      "span",
      "p",
      "b",
      "i",
      "em",
      "strong",
      "a",
      "br",
      "ul",
      "ol",
      "li",
      "img",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "table",
      "thead",
      "tbody",
      "tr",
      "th",
      "td",
      "code",
      "pre",
      "blockquote",
      "hr",
      "svg",
      "path",
      "circle",
      "rect",
      "line",
      "polyline",
      "polygon",
      "g",
      "defs",
      "use",
      "symbol",
      "text",
      "tspan",
    ],
    ALLOWED_ATTR: [
      "class",
      "style",
      "href",
      "target",
      "rel",
      "src",
      "alt",
      "width",
      "height",
      "viewBox",
      "fill",
      "stroke",
      "stroke-width",
      "d",
      "cx",
      "cy",
      "r",
      "x",
      "y",
      "x1",
      "y1",
      "x2",
      "y2",
      "points",
      "transform",
      "xmlns",
      "id",
      "clip-path",
      "opacity",
    ],
  });
}
