/**
 * Shared authentication helpers for Playwright tests.
 *
 * Test users must exist in Supabase with these credentials:
 *   test-owner@example.com   → role: owner
 *   test-admin@example.com   → role: admin
 *   test-mod@example.com     → role: moderator
 *   test-editor@example.com  → role: editor
 *   test-member@example.com  → role: member
 *   test-guest@example.com   → role: guest
 * All passwords: TestPassword123!
 *
 * For storageState-based auth (faster, no login per test):
 *   import { storageStatePath } from "./helpers/auth";
 *   test.use({ storageState: storageStatePath("member") });
 */
import type { Page } from "@playwright/test";
import path from "path";

export const TEST_PASSWORD = "TestPassword123!";

export const TEST_USERS = {
  owner: { email: "test-owner@example.com", role: "owner" },
  admin: { email: "test-admin@example.com", role: "admin" },
  moderator: { email: "test-mod@example.com", role: "moderator" },
  editor: { email: "test-editor@example.com", role: "editor" },
  member: { email: "test-member@example.com", role: "member" },
  guest: { email: "test-guest@example.com", role: "guest" },
} as const;

export type TestRole = keyof typeof TEST_USERS;

/**
 * Login as a specific test user via the /auth/login page.
 * Waits for redirect away from the login page before returning.
 */
export async function loginAs(page: Page, role: TestRole): Promise<void> {
  const user = TEST_USERS[role];
  await page.goto("/auth/login");
  await page.waitForLoadState("domcontentloaded");

  const identifierInput = page.locator("#identifier");
  const passwordInput = page.locator("#password");

  /* If already on a non-login page, we may be logged in */
  if ((await identifierInput.count()) === 0) return;

  await identifierInput.first().fill(user.email);
  await passwordInput.first().fill(TEST_PASSWORD);
  await page.locator('button[type="submit"]').first().click();
  await page.waitForURL((url) => !url.pathname.includes("/auth/login"), { timeout: 15000 });
  await page.waitForLoadState("domcontentloaded");
}

/**
 * Navigate to /auth/login to effectively "log out" (public page, clears auth redirect).
 */
export async function logout(page: Page): Promise<void> {
  await page.goto("/auth/login");
  await page.waitForLoadState("domcontentloaded");
}

/**
 * Returns the path to a pre-authenticated storage state file for a given role.
 * These files are generated by `tests/auth.setup.ts`.
 *
 * Usage:
 *   test.use({ storageState: storageStatePath("member") });
 */
export function storageStatePath(role: TestRole): string {
  return path.join(__dirname, "..", ".auth", `${role}.json`);
}
